#!/bin/bash

if [[ $4 = *"mir"* ]]; then
  echo "It's there!"
fi

if [[ $4 = *"hel18"* ]]; then
  cd /home/nader/drive/bin/18/helios2018-bin && ./auto.sh -h $1 -p $2 -P $3 &> /dev/null
fi
if [[ $4 = *"hel17"* ]]; then
  cd /home/nader/Documents/bin/17/helios2017-bin && ./auto.sh $1 $2 $3 &> /dev/null
fi
if [[ $4 = *"hfut"* ]]; then
  cd /home/nader/drive/bin/17/hfutengine && ./auto.sh $1 $2 $3 &> /dev/null
fi
if [[ $4 = *"mt17"* ]]; then
  cd /home/nader/Documents/bin/17/mt2017 && ./auto.sh $1 $2 $3 &> /dev/null
fi
if [[ $4 = *"alice"* ]]; then
  cd /home/nader/Documents/bin/17/alice && ./auto.sh $1 $2 $3 &> /dev/null
fi
if [[ $4 = *"wr"* ]]; then
  cd /home/nader/Documents/bin/17/wrightEagle && ./auto.sh $1 $2 $3 &> /dev/null
fi
if [[ $4 = *"oxsy"* ]]; then
  cd /home/nader/Documents/bin/17/oxsy && ./auto.sh $1 $2 $3 &> /dev/null
fi

if [[ $4 = *"fra"* ]]; then
  cd /home/nader/drive/bin/18/fraunited && ./startAll &> /dev/null
fi

if [[ $4 = *"namira"* ]]; then
  cd /home/nader/Documents/bin/17/namira && ./auto.sh $2 $3 &> /dev/null
fi
if [[ $4 = *"kn18"* ]]; then
  cd /home/nader/drive/bin/18/asia-material-KN2C/KN2C2018-Bin && ./startAll $2 $3 &> /dev/null
fi
if [[ $4 = *"mt18"* ]]; then
  cd /home/nader/drive/bin/18/mt && ./auto.sh $1 $2 $3 &> /dev/null
fi
if [[ $4 = *"mt19"* ]]; then
  cd /home/nader/drive/bin/19/mt && ./auto.sh $1 $2 $3 &> /dev/null
fi
if [[ $4 = *"it18"* ]]; then
  cd /home/nader/drive/bin/18/itandroids && ./auto.sh $1 $2 $3 &> /dev/null
fi
if [[ $4 = *"ox18"* ]]; then
  cd /home/nader/drive/bin/18/oxsy && ./auto.sh $1 $2 $3 &> /dev/null
fi
if [[ $4 = *"cr18"* ]]; then
  echo 'nader' $2
  cd /home/nader/drive/bin/18/cyrus_round_3/src && ./auto.sh -p $2 -P $3 &> /dev/null
fi

sleep 5
