#!/bin/bash
echo "*******************"
echo $*
# ssh -f $1 "ulimit -t 300 && ulimit -c unlimited && cd /home/nader/git/cyrus/cyrus/src/ && ./auto.sh -h $1 -p $2 -P $3"
#cd /home/nader/git/cyrus/cyrus/src/ && ./auto.sh -h $1 -p $2 -P $3 



if [[ $4 = *"cr18"* ]]; then
  cd /home/nader/drive/bin/18/cyrus_round_3/src && ./auto.sh -p $2 -P $3 &> /dev/null
fi
if [[ $4 = *"cr19"* ]]; then
  cd /home/nader/workspace/robo/cc/cyrus/src && ./auto.sh -p $2 -P $3 &> /dev/null
fi
sleep 5
